name: Deploy

on:
  workflow_run:
    workflows: ["Publish Docker image"]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    steps:
    - name: SSH connect and update Docker image
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        USERNAME: ${{ secrets.VPS_USERNAME }}
        PORT: ${{ secrets.VPS_PORT }}
        KEY: ${{ secrets.VPS_SSHKEY }}
        script: |
          docker pull durianice/chat-next-web:latest
          docker stop chat-next-web
          docker rm chat-next-web
          docker run -d -p 3000:3000 \
            -e OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
            -e CODE=${{ secrets.WEB_PWD }} \
            --name chat-next-web \
            durianice/chat-next-web